#![no_std]

/// Bindings generated by bindgen.
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
pub mod bindings;

pub mod print;
pub mod sync;
pub mod thread;
pub mod time;

pub use concat_idents::concat_idents;

pub(crate) mod macros;
